apache/brooklyn-docs

- README.md
- _build/build.sh
- _build/htmlproof-brooklyn.sh
- _build/serve-public-site.sh
- _includes/base-head.html
- _includes/footer.html
- _includes/topmenu.html
- _layouts/website-landing.html
- guide/dev/code/submodules.md
- website/community/how-to-contribute-docs.md
- website/developers/committers/merging-contributed-code.md
- website/developers/how-to-contribute.md
- website/developers/links.md
these docs are also pushed to be live at the /v/0.9.0-SNAPSHOT/ endpoint
> update many docs to point at new locations and have better instructions

- _includes/base-head.html
- guide/start/running.md
* Restricted the glossary to getting started pages
* Updated vagrant url & related doc
> Corrections to Getting Started & Vagrant URL

- guide/yaml/index.md
- guide/yaml/salt/about-salt.md
- guide/yaml/salt/creating-salt-blueprints.md
- guide/yaml/salt/index.md
See https://issues.apache.org/jira/browse/BROOKLYN-217.
This commit merges code from incubator-brooklyn, following the move to the new repos
after graduation. As such, it unfortunately loses the commit history, but the code
is based on the work done by Hadrian Zbarcea.  See the Jira link above for history
and discussion.
> Documentation for initial support for SaltStack.

- guide/ops/locations/index.md
documents the clarification implemented in https://github.com/apache/brooklyn-server/pull/7
> document location inheritance better, including recent fix

- guide/misc/release-notes.md
> VanillaWindowsProcess.WINRM_PORT sensor renaming

- guide/ops/catalog/index.md
- guide/ops/locations/index.md
Added format for the getting started vagrant byon to a catalog entry example
> Location example for the catalog

- guide/dev/env/maven-build.md
Add notes about building RPM packages.
> Update maven-build.md with RPM notes.

- guide/yaml/ansible/creating-ansible-blueprints.md
Add guidelines and examples for how to do multiple playbooks and roles with AnsibleEntity.
> Multi-playbook and role documentation

- guide/ops/locations/byon.md
- guide/ops/locations/clouds.md
- guide/ops/locations/index.md
- guide/ops/locations/localhost.md
Related to https://github.com/apache/brooklyn-ui/pull/17
> Add mention of location wizard into the documentation

- guide/ops/cli/cli-ref-guide.md
- guide/ops/cli/cli-usage-guide.md
> add -P prefix to invoke params in br reference/example

- guide/ops/locations/more-clouds.md
Documentation for the changes made in https://github.com/apache/brooklyn-server/pull/53
> Describe SoftLayerSameVlanLocationCustomizer configuration

- LICENSE
- guide/start/running.md
Minor wording changes around RPM install
> Minor wording changes around RPM install

- guide/start/running.md
> Additional getting started tabs

- guide/yaml/winrm/index.md
Some details about CredSSP protocol: https://msdn.microsoft.com/en-us/library/cc226764.aspx
> Clarifications on using Invoke-Command with CredSSP

- guide/ops/locations/clouds.md
- guide/ops/persistence/index.md
- guide/start/running.md
- guide/yaml/chef/about-chef.md
- website/documentation/increase-entropy.md
Corrected references to Apache Brooklyn @richardcloudsoft
> Corrected brooklyn references

- guide/ops/brooklyn_properties.md
Documentation for entitlements changes in https://github.com/apache/brooklyn-server/pull/108.
> Describe "user" entitlement group

- guide/ops/cli/index.md
- guide/start/running.md
Added links to the separate CLI download locations
> Added CLI download locations

- guide/ops/catalog/index.md
- guide/start/running.md
Changes for when the deb file is added as an install option
> Getting started for deb distribution - For review

- _config.yml
- _includes/fields.md
- _plugins/brooklyn_metadata.rb
- _plugins/page_structure.rb
- guide/misc/download.md
- guide/misc/release-notes.md
- website/download/index.md
- website/download/verify.md
- website/meta/versions.md
Various changes applied to the 0.9.0 site to get the website and docs updated for the new release.
> Changes on 0.9.0

- guide/ops/server-cli-reference.md
Adds --bindAddress launch flag which was not documented elsewhere.
>  Adds --bindAddress flag to server-cli-reference.md

- guide/ops/locations/clouds.md
- guide/ops/persistence/index.md
- guide/start/running.md
- guide/yaml/chef/about-chef.md
- website/documentation/increase-entropy.md
See [PR41](https://github.com/apache/brooklyn-docs/pull/41)
> 0.9.0 Corrected brooklyn references

- guide/ops/cli/index.md
- guide/start/running.md
See [PR42](https://github.com/apache/brooklyn-docs/pull/42)
> 0.9.0 Added CLI download locations

- guide/start/running.md
See [PR51](https://github.com/apache/brooklyn-docs/pull/51)
> 0.9.0 Added notices for RPMs in snapshot releases

- guide/ops/catalog/index.md
Addresses review comments in #49 
/cc @geomacy
> Extend catalog include docs

- guide/ops/locations/_clouds.md
Added instructions to give a custom name to VMs in a location
> Machine naming in locations

- guide/ops/locations/_clouds.md
- guide/ops/locations/_more-clouds.md
- guide/yaml/test/test-entities.md
- guide/yaml/winrm/index.md
> Openstack network documentation

- guide/yaml/test/usage-examples.md
Paths used relative links, updated to use {{ site.path.guide }}
> Updated paths for usage-examples

- guide/yaml/test/test-entities.md
Depends on https://github.com/apache/brooklyn-server/pull/269
> Add notEqual assertion to test entities

- guide/java/archetype.md
The doc will now more explicitly show adding the JAR to Brooklyn
> Updated the maven archetype doc

- guide/java/policies.md
- guide/ops/brooklyn_properties.md
- guide/ops/production-installation.md
- guide/ops/requirements.md
- guide/start/blueprints.md
- guide/start/managing.md
- guide/start/running.md
- guide/yaml/winrm/index.md
- guide/yaml/yaml-reference.md
Changed some relative links to absolute links.
I have run a link checker on the docs with and without these changes. Without these changes there is one more broken link.
> Various fixes. Mainly changing relative links to absolute links

- guide/index.md
- guide/ops/brooklyn_properties.md
- guide/ops/https.md
- guide/ops/index.md
- guide/ops/osgi-configuration.md
- guide/ops/osgi.md
Plus a few more details on key generation.
> Add config instructions for HTTPS on Karaf.

- guide/yaml/yaml-reference.md
This depends on https://github.com/apache/brooklyn-server/pull/358
> Add documentation about pinned field for Brooklyn parameters

- guide/yaml/custom-entities.md
- guide/yaml/example_yaml/vanilla-bash-netcat-env.yaml
Depends on https://github.com/apache/brooklyn-server/pull/216
> Document shell.env json serialization behaviour.

- guide/ops/locations/_AWS.md
- guide/ops/locations/_GCE.md
- guide/ops/locations/_azure-ARM.md
- guide/ops/locations/_azure-classic.md
- guide/ops/locations/_cloudstack.md
- guide/ops/locations/_ibm-softlayer.md
- guide/ops/locations/_openstack.md
This re-orders the locations menu items to a more sensible order since the addition of Azure ARM.
> Re-order locations

- guide/yaml/entity-configuration.md
_I'm about to create the bug report, and will update the text to reference that!_
> Adds “DSL Evaluation of Inherited Config” section [WIP]

- guide/yaml/test/test-entities.md
Accompanies https://github.com/apache/brooklyn-server/pull/619.
> Documentation on greaterThan and lessThan test assertions

- guide/yaml/test/test-entities.md
See discussion in https://github.com/apache/brooklyn-server/pull/589
> Improve test-entities matcher docs, for regex

- guide/ops/security-guidelines.md
Ssh access should be strongly limited.
> Security guidelines

- guide/blueprints/config-files.md
- guide/blueprints/entity-configuration.md
- guide/blueprints/java/archetype.md
- guide/blueprints/winrm/index.md
- guide/ops/troubleshooting/deployment.md
- guide/ops/troubleshooting/slow-unresponsive.md
A full guide to using template files in blueprints.
> Guide to template files

- guide/ops/production-installation.md
https://issues.apache.org/jira/browse/BROOKLYN-505
> Document JCE requirements

- guide/ops/requirements.md
- guide/ops/troubleshooting/slow-unresponsive.md
- website/developers/committers/release-process/prerequisites.md
- website/download/index.md
> Point to currently supported Java 8

- guide/locations/index.md
- guide/locations/provisioned-machine-requirements.md
(We could also a link to this new page from the troubleshooting index.html. I've not done that here.)
> BROOKLYN-477: add “Provisioned Machine Requirements”

- guide/ops/requirements.md
Addresses comments in #190 and fixes merge conflicts there
> Java8 and OS

- guide/locations/_location-customizer-security-groups.md
- guide/locations/_location-customizers.md
- guide/locations/_special-locations.md
- guide/locations/index.md
- guide/locations/jclouds-location-customizers/index.md
- guide/locations/machine-location-customizers/index.md
Updates the structure from #119.
> Update location structure

- guide/blueprints/enrichers.md
Changes docs to match [brooklyn-server#763](https://github.com/apache/brooklyn-server/pull/763)
> Add first addition to Aggregator

- guide/start/blueprints.md
> Minor change to be more accurate on contents of BP repo

- guide/blueprints/policies.md
- style/css/_basic.scss
Tidy up documentation around policies
> Policies tidy

- guide/blueprints/clusters-and-policies.md
- guide/blueprints/example_yaml/appserver-clustered-w-db-concise.yaml
- guide/blueprints/example_yaml/appserver-clustered-w-db.yaml
- guide/blueprints/example_yaml/appserver-w-db-other-flavor.yaml
- guide/blueprints/example_yaml/appserver-w-db.yaml
- guide/blueprints/example_yaml/appserver-w-policy.yaml
- guide/blueprints/multiple-services.md
- guide/blueprints/test/example_yaml/testcases/getting-started-test-example.yaml
- guide/ops/cli/cli-usage-guide.md
- guide/ops/externalized-configuration.md
- guide/ops/gui/_my-web-cluster.yaml
- guide/ops/gui/_my-web-cluster2.yaml
- guide/start/_my-web-cluster.yaml
- guide/start/_my-web-cluster2.yaml
so far just explains it, need to use it
> explain and use the `brooklyn-demo-sample` external provider

- _config.yml
- guide/misc/download.md
- guide/misc/release-notes.md
- guide/ops/upgrade.md
- style/js/public.js
- website/download/index.md
- website/download/verify.md
- website/meta/versions.md
Ensures correct version numbers in all locations, correct artifact names, other minor tweaks. Updates Google Analytics tracking code.
> Website 0.12.0 updates

- guide/blueprints/entity-configuration.md
- guide/blueprints/example_yaml/fabric-with-multiple-locations.yaml
Updated example war's URL + fix wrong config key's name
> Update outdated blueprint examples

- guide/blueprints/_elect-primary-policies.md
- guide/blueprints/policies.md
Documentation for https://github.com/apache/brooklyn-server/pull/879
This has been developed in the field but is now generalized to the point I think it will be useful for many cases.
@aledsage @grkvlt -- particularly welcome feedback from y'all as you've done similar things I know
> document the new ElectPrimaryPolicy and related items

- guide/locations/_AWS.md
Document how to specify the EBS boot volume size on AWS
> Specify EBS boot volume size

- guide/blueprints/example_yaml/vanilla-bash-netcat-catalog.bom
Fixed by adding all required sensors to triggerSensors
> Race condition causing main.uri to be null

- community/gsoc.md
Update to note that applications are now open.
> Update GSoC information page

- guide/locations/_azure-ARM.md
Provides the command used to change the Azure active directory
application password used for API access
> Document Azure ad app password reset

- guide/blueprints/winrm/index.md
See https://issues.apache.org/jira/browse/BROOKLYN-592
> BROOKLYN-592: add to WinRM troubleshooting

- guide/concepts/configuration-sensor-effectors.md
- guide/concepts/dependent-configuration.md
- guide/concepts/execution.md
- guide/concepts/lifecycle-managementcontext.md
* fix spelling/typos
* deleting stray words and symbols
* indicate to click to view an image full size
> guide/concepts: fix typos and add click-to-view-image clarification

- guide/blueprints/entity-configuration.md
- guide/blueprints/yaml-reference.md
minor things I found that could be clearer
> some blueprinting tweaks

- developers/code/git-more.md
- developers/committers/merging-contributed-code.md
- developers/committers/release-process/vote.md
- developers/how-to-contribute.md
This follows move to gitbox, see
https://lists.apache.org/thread.html/3d87de62fa3330222a972ed98e63907107ca5951f0bdf099972ae426@%3Cdev.brooklyn.apache.org%3E
> Change git-wip-us.apache.org to gitbox.apache.org

- guide/blueprints/test/test-entities.md
This requires https://github.com/apache/brooklyn-server/pull/1063
> Update documentation to match new parameters for TestCase entity

- Dockerfile
- README.md
This also update the instructions on how to use the new docker image to build and test the website
> Add Dockerfile to build the website with docker

- guide/ops/cli/cli-ref-guide.md
- guide/ops/cli/cli-usage-guide.md
Updates the CLI doc after https://github.com/apache/brooklyn-client/pull/77 changes
> Upgraded login options for oauth

- guide/blueprints/advanced-example.md
- guide/blueprints/clusters.md
- guide/blueprints/configuring-vms.md
- guide/blueprints/custom-entities.md
- guide/blueprints/test/index.md
- guide/blueprints/yaml-reference.md
- guide/concepts/configuration-sensor-effectors.md
- guide/ops/configuration/index.md
- guide/start/managing.md
- guide/start/policies.md
This time only the most trivial changes. Replaces #287.
> proofreading round 1 (2nd try)

- guide/blueprints/entity-configuration.md
- guide/blueprints/multiple-services.md
- guide/blueprints/winrm/index.md
> proofreading round 3

- guide/ops/configuration/brooklyn_cfg.md
Describes how to config the session expiring and what is the its default behavior
> Session expiring configuration

- book.json
Added version 1.0.0 to the combo list and setting it up as current and stable version
> Added version 1.0.0 as latest version

- guide/ops/configuration/index.md
until required startup services are available
> documentation for options that delay catalog init / rebind 

- guide/ops/configuration/brooklyn_cfg.md
Can handle multiple ldap realms
Can have a static login page instead of WWW_Authenticate header
> Description of recent login and ldap changes

- guide/blueprints/yaml-reference.md
docs for https://github.com/apache/brooklyn-ui/pull/210 (and some previous work)
> add docs for composer annotations and hints

- guide/ops/logging.md
> Initial logbook setup guide

- guide/ops/logging.md
- guide/ops/security-guidelines.md
> Added mention of the trace configuration being provided

- guide/locations/_clouds.md
> Fix default value of destroyOnFailure in docs

- guide/ops/configuration/brooklyn_cfg.md
Doc for https://github.com/apache/brooklyn-server/pull/1245
> Adding user_name_regex config key doc

- guide/locations/_cloudstack.md
- guide/locations/_ibm-softlayer.md
> Fix selection in Location chapters

- guide/ops/configuration/brooklyn_cfg.md
Add docs for https://github.com/apache/brooklyn-server/pull/1252
> new domain_name_regex config key doc

- guide/ops/security-guidelines.md
docs for https://github.com/apache/brooklyn-server/pull/1258
> documentation for new keys controlling sensitive information display

- guide/blueprints/policies/available_policies.md
> Docs for nginx-multi-upstream-sync policy

- guide/blueprints/yaml-reference.md
> Added mention that there are places where DSL expressions are not

- _plugins/jekyll_relative_links.rb
> Do not replace relative links on the same page

- guide/ops/cli/cli-ref-guide.md
> Display top-level sections as chidlren only

- guide/locations/_clouds.md
- guide/ops/configuration/brooklyn_cfg.md
documentation for https://github.com/apache/brooklyn-server/pull/1347
> add docs for cert configuration

- _plugins/jekyll_relative_links.rb
- guide/locations/_azure-ARM.md
- guide/ops/troubleshooting/detailed-support-report.md
> Fix url to cli-ps-findimage in Azure locations

- guide/locations/_clouds.md
Depends on https://github.com/apache/brooklyn-server/pull/1354
> Update instructions regarding SSH and SCP executables

- guide/blueprints/workflow/steps/steps.yaml
Builds on https://github.com/apache/brooklyn-server/pull/1369
> expand docs for `let` step

- guide/blueprints/workflow/variables.md
- workflow variables output fix
> Workflow documentation fixes found

- guide/blueprints/workflow/common.md
- guide/blueprints/workflow/nested-workflow.md
> Link fix for 'Predicate DSL' page in conditions page

- guide/blueprints/blueprinting-tips.md
- guide/blueprints/java/bundle-dependencies.md
- guide/blueprints/setting-locations.md
- guide/blueprints/winrm/client.md
- guide/blueprints/workflow/examples/oauth/index.md
- guide/blueprints/workflow/steps/index.md
- guide/blueprints/yaml-reference.md
- guide/locations/_GCE.md
- guide/locations/_azure-ARM.md
- guide/ops/logging/index.md
- guide/ops/troubleshooting/increase-entropy.md
- guide/start/blueprint_locations/_index.md
fixing some internal and external links
> further doc fixes to fix links

- guide/locations/_AWS.md
> remove section about legacy account as it is now fully retired

- style/js/public.js
See https://issues.apache.org/jira/browse/BROOKLYN-635
> Remove Google Analytics Brooklyn Website (BROOKLYN-635)
