guide/start/example_yaml/mycluster.yaml, guide/start/policies.md, website/documentation/glossary.md
Walks through auto-repair, auto-recover and auto-scaling of a simple tomcat cluster.
Note the "TODO"s:
* How do we make the yaml example easier to copy-paste? As with the example at http://brooklyn.apache.org/learnmore/blueprint-tour.html, there is no "copy to clipboard" action; and highlighting the text has the unfortunate effect of also copying he headings on the left (rather than just the yaml).
* Why doesn't the activity view show the `restart()` effector call made by the `ServerRestarter` policy? That part of the guide is commented out.
=> Updates the getting started “policies” example.

guide/yaml/ansible/about-ansible.md, guide/yaml/ansible/creating-ansible-blueprints.md, guide/yaml/ansible/index.md, guide/yaml/index.md, guide/yaml/salt/creating-salt-blueprints.md
These are the document updates for the Ansible integration work, they describe in broad detail the way Brooklyn can now integrate with Ansible, and what configuration  options there are for ansible within blueprints.
=> Initial Ansible integration documents.

Gemfile, guide/dev/env/maven-build.md, guide/misc/download.md, website/developers/committers/release-process/prerequisites.md, website/developers/committers/release-process/publish-temp.md, website/developers/committers/release-process/publish.md, website/developers/committers/release-process/vote.md
See https://issues.apache.org/jira/browse/BROOKLYN-224.
Note there are still some references to "incubator" around voting processes that I was unsure about changing, e.g. references to general@incubator.
=> First pass at fixes for broken links due to incubator change.

website/community/mailing-lists.md
- uses http://markmail.org/
- spotted the idea on http://couchdb.apache.org
=> add mailing list search box to website

_build/build-pdf.sh, _build/build.sh, _build/buildPDF.sh, style/css/printable.css
Produces a second, more printer friendly version of the PDF documentation. Uses an additional style sheet to remove colours and formatting unsuitable for printing.
=> Printable PDF Generation

guide/start/running.md
Calling it "local install" was confusing - people didn't realise you could install the binaries anywhere.
=> Minor wording changes around option of installing binaries in own env

guide/yaml/winrm/index.md
=> Details about using CredSSP in Windows

style/js/catalog/common.js, website/learnmore/catalog/catalog-item.html
https://brooklyn.apache.org/learnmore/catalog is currently broken for entities with config keys without default values (e.g. [BrooklynNode](https://brooklyn.apache.org/learnmore/catalog/catalog-item.html#!entities/org.apache.brooklyn.entity.brooklynnode.BrooklynNode)).
=> Fixes handling of undefined values in templates

guide/start/running.md
RPMs are not available in snapshot releases, this is now reflected with a notice and redirection.
=> Added a notice for RPMs in snapshot releases

guide/yaml/custom-entities.md
This PR tries to document the solution for [BROOKLYN-263](https://issues.apache.org/jira/browse/BROOKLYN-263) issue that is implemented by [brooklyn-server#136](https://github.com/apache/brooklyn-server/pull/136).
=> Updating port inferencing documentation

guide/yaml/creating-yaml.md
Found a broken link on the Brooklyn website https://brooklyn.apache.org/v/latest/yaml/creating-yaml.html  - its the git-clone link towards the bottom.
Current is:  https://brooklyn.apache.org/v/latest/dev/code/index.html
It should be:  https://brooklyn.apache.org/developers/code/index.html
=> Corrected broken link 'git-clone'

guide/ops/locations/_special-locations.md
In particular, how it can be used with the “availability zone” extension
to round-robin across the targets.
=> Improve multi-location docs

guide/ops/index.md, guide/ops/requirements.md, guide/ops/starting-stopping-monitoring.md
Some additions to the User Guide "Operations" section, covering starting, monitoring and stopping the server, and a discussion of its disk space usage.
=> Ops guides updates for monitoring and disk space

guide/java/gist_generator/gist_generator.bom, guide/misc/osgi.md, guide/ops/catalog/index.md, guide/ops/externalized-configuration.md, guide/yaml/entity-configuration.md, guide/yaml/example_yaml/brooklyn-elasticsearch-catalog.bom, guide/yaml/example_yaml/brooklyn-elk-catalog.bom, guide/yaml/example_yaml/brooklyn-kibana-catalog.bom, guide/yaml/example_yaml/brooklyn-logstash-catalog.bom, guide/yaml/example_yaml/vanilla-bash-netcat-catalog.bom
See email discussion on dev@brookyn, subject "[PROPOSAL] catalog YAML format consistency".
This just does minor changes.
The biggest change is adding itemType in all our examples, and updates the docs to say that it's compulsory. It also wraps all the version numbers in quotes, and makes the metadata order more consistent (id, then version, then itemType).
Similar PRs to follow in the other repos, to change their brooklyn.catalog examples to include itemType.
=> Catalog format more consistent

_includes/java_link.html, _plugins/brooklyn_metadata.rb, guide/java/entities.md, guide/misc/javadoc/index.md, guide/ops/brooklyn_properties.md, guide/ops/production-installation.md, guide/yaml/ansible/index.md, guide/yaml/blueprinting-tips.md, guide/yaml/configuring-vms.md, guide/yaml/creating-yaml.md, guide/yaml/salt/index.md
Fixed broken links throughout the docs
=> Fixed broken links

guide/ops/locations/_GCE.md, guide/ops/locations/_ssh-keys.md, guide/ops/production-installation.md, guide/ops/requirements.md, guide/ops/troubleshooting/increase-entropy.md, guide/ops/troubleshooting/increase-system-resource-limits.md, guide/ops/troubleshooting/index.md, guide/ops/troubleshooting/slow-unresponsive.md, website/documentation/faq.md
They were previously in website/documentation/increase-entropy.md and
in the faq. Now they are top-level pages in troubleshooting.
=> Move entropy/ulimit docs to troubleshooting

guide/ops/troubleshooting/deployment.md
Added new troubleshooting section in response to CentOS 7 provisioning error.
=> added more to deployment troubleshooting section

guide/ops/locations/_openstack.md
If a user follows these instructions after following the previous devtest ones, these will fail to work. If they are instructed to use the `patch` folder, they will.
=> Change Mitaka instructions

guide/start/brooklyn.properties
* Tell people that the catalog is the recommended way to configure
locations.
* Move AWS out of “Getting Started”. The user can add a location via
the UI; that is what we should encourage.
* Remove HP Cloud, because that service no longer exists.
* Fix a few links.
* installDevUrandom now defaults to true; update comment.
* comment out everything (including AWS creds example) as we want to
encourage use of catalog.
=> Tidy up example brooklyn.properties

guide/misc/release-notes.md
As tested in https://github.com/apache/brooklyn-server/pull/411
The failure to coerce a default value is a bug, but the fix might catch people out who used `$brooklyn:config` for ports in places without specifying custom config so worth adding to release notes.
=> document change to default coercion behaviour

_layouts/base.html, guide/start/policies.md, guide/start/running.md, style/css/_code_blocks.scss
inspired by #97 (and replacing it) this uses the proper multi-line bash char, and ensures these chars are removed on copy-paste
uses a nice JS `oncopy` trick mentioned in the comments on that PR
=> Remove bash prompt chars

guide/start/policies.md
as discussed in #97 -- the old args looked really strange, at least on the os x `curl`.
would appreciate feedback from any of @drigodwin @duncangrant @Graeme-Miller @aledsage @grkvlt who might have some insight as to whether the old args were there for a reason.
=> tidy curl args

guide/ops/troubleshooting/increase-system-resource-limits.md
The brooklyn user is the most common one used for running instances (created by the rpm & deb packages).
=> Use brooklyn user for easier copy&paste

website/community/mailing-lists.md
lists.apache.org is perhaps a bit nicer and more functional than mail-archives.apache.org.
=> Link to lists.a.o instead of mail-archives.a.o

guide/yaml/yaml-reference.md
Page reads just as well without Brooklyn ref.
=> fixed mis-spelling by removing Broo(o)klyn

guide/ops/locations/_GCE.md, guide/ops/locations/_azure-ARM.md, guide/ops/locations/_azure-classic.md
Adds Azure Classic and Azure ARM usage details to the documented locations.
=> Add Azure Classic and ARM docs

guide/misc/release-notes.md
Can't be communicated to the user by deprecating APIs or logging.
Follow up to https://github.com/apache/brooklyn-server/pull/562.
=> Add deprecated functionality which can't be communicated to the user otherwise

guide/yaml/custom-entities.md, guide/yaml/yaml-reference.md
`org.apache.brooklyn.core.sensor.windows.WinRmCommandSensor` is already listed in `brooklyn-docs/guide/yaml/yaml-reference.md` but it could be nice to have it here as well.
=> Brooklyn.initializers example with sensor from windows command

guide/dev/tips/index.md, guide/java/policies.md
Adds documentation to address the problem described by https://issues.apache.org/jira/browse/BROOKLYN-458.
Questions for reviewers: 
* Should the "Enrichers" list be moved to its own page entirely, rather than being on the "Policies" page?
* Should the workaround listed in https://issues.apache.org/jira/browse/BROOKLYN-458?focusedCommentId=15938141&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15938141 be included in the docs?
=> Add docs for enricher.producer values

guide/ops/locations/_clouds.md, guide/ops/locations/_openstack.md
Removed obsolete openstack-mitaka-nova section.
=> Update jclouds 1.9.x links to point to jclouds 2.0.x

website/meta/versions.md
Snapshot Versions links are defunct and not useful (see: [BROOKLYN-443](https://issues.apache.org/jira/browse/BROOKLYN-443)). I propose we remove them.
=> Remove snapshot docs link

guide/ops/osgi.md
Put osgi mode debugging in separate section
Add JAVA_DEBUG_PORT description.
Recommend up to date JAVA_DEBUG_OPTS flags
Those are the same used with `bin/karaf debug`
---
-Xnoagent Ignored in Oracle Java
http://www.oracle.com/technetwork/java/javase/tech/faqs-jsp-142584.html#QC4
-Xnoagent Disables old JDB debugger in IBM Java
https://www.ibm.com/support/knowledgecenter/SSYKE2_7.0.0/com.ibm.java.zos.70.doc/diag/appendixes/cmdline/Xnoagent.html
Recommend using agentlib:jdwp over runjdwp:transport
The above is said to be deprecated in Java 6
http://docs.oracle.com/javase/6/docs/technotes/guides/jpda/conninv.html#Invocation
In Java 8 docs only agentlib:jdwp is mentioned
IBM also recommends using agentlib:jdwp
https://www.ibm.com/developerworks/opensource/library/os-eclipse-javadebug/index.html …
=> Recommend up to date JAVA_DEBUG_OPTS flags

guide/index.md
Previously, there was no link to "locations" in the menu on the right, or at http://brooklyn.apache.org/v/latest/index.html
(However, there is already a link in the drop-down at the top for "Documentation", called "Deploying Blueprints". That name isn't consistent with "Locations" in the contents page, but I think we can live with that for now.)
=> Add “guide/locations” link to contents page

guide/blueprints/advanced-example.md, guide/blueprints/example_yaml/brooklyn-elasticsearch-catalog.bom, guide/blueprints/example_yaml/brooklyn-elk-catalog.bom, guide/blueprints/example_yaml/brooklyn-kibana-catalog.bom, guide/blueprints/example_yaml/brooklyn-logstash-catalog.bom
This is required as https://github.com/brooklyncentral/brooklyn-elk has been updated and the examples are no longer accurate.
=> Fixed advanced example by shipping blueprints in repo

guide/blueprints/catalog/bundle.md, guide/blueprints/catalog/versioning.md
docs re cleared-up OSGi/semver/maven versioning, as per ML
(this is WIP because the corresponding code is not yet written; however review here could be useful)
=> Versioning

guide/blueprints/policies.md
Docs for [brooklyn-server#822](https://github.com/apache/brooklyn-server/pull/822)
=> Add docs for Scheduled and PeriodicEffectorPolicy

guide/blueprints/custom-entities.md, guide/blueprints/example_yaml/vanilla-bash-netcat-file.yaml, guide/blueprints/example_yaml/vanilla-bash-netcat-more-commands.yaml
And some other tidies of custom-entities doc.
These docs are primarily for the change in https://github.com/apache/brooklyn-server/pull/824. It also documents how to wire up an alternative http-based polling for health.
IT also does some other tidy up. For example, `./start.sh` is no longer the default value for `launch.command` so we need to fix that example.
=> Document `sshMonitoring.enabled`

guide/locations/_azure-ARM.md
The existing instructions are for Azure CLI 1.0. Searching for "Azure CLI" returns hits for 2.0 so it's likely our users will end up with CLI 2.0.
=> Update Azure ARM documentation for Azure CLI 2.0

guide/misc/download.md, guide/ops/index.md, guide/ops/upgrade.md, website/download/index.md
This requires the `paths.html` page available with #210
=> Add update instructions for RPM/DEB and bin distribution

guide/misc/release-notes.md
replaces #208 
updated application unique id note as per review comment there, also see https://github.com/apache/brooklyn-server/pull/782
no objection @drigodwin if you want to expand to link to jclouds release notes; easy enough for a user to find however if they want to so not necessary imo
=> update release notes for 0.12, adding a few things i'm aware of

guide/ops/externalized-configuration.md
Minor fix to rename properties to cfg.
=> Update brooklyn.properties to brooklyn.cfg

guide/blueprints/advanced-example.md, guide/blueprints/ansible/creating-ansible-blueprints.md, guide/blueprints/example_yaml/brooklyn-elk-catalog.bom
Since Brooklyn 0.12.0 ([this PR](https://github.com/apache/brooklyn-server/pull/819) precisely) some config keys' name have been deprecated generated a warning when installing a blueprint using those. 
This fixes it by using the new names.
=> Update config keys' deprecated names

guide/styles/policy-tour.less
The policies page example was not using the colour defined within the `variables.less` file, this fixes it.
=> Use colour from variables.less for blueprint tour

guide/blueprints/ansible/creating-ansible-blueprints.md
Does 3 things:
- update `serviceType` to `type`
- update `start.latch` to `latch.start`
- use backticks to have syntax highlighting on YAML examples
=> Update YAML example to newer syntax

guide/blueprints/example_yaml/appserver-clustered-w-db-concise.yaml, guide/blueprints/example_yaml/appserver-clustered-w-db.yaml, guide/blueprints/example_yaml/appserver-configured.yaml, guide/blueprints/example_yaml/appserver-w-db-other-flavor.yaml, guide/blueprints/example_yaml/appserver-w-db.yaml, guide/blueprints/example_yaml/appserver-w-policy.yaml, guide/blueprints/example_yaml/brooklyn-elk-catalog.bom, guide/blueprints/test/example_yaml/entities/testeffector-entity.yaml, guide/blueprints/test/example_yaml/testcases/effector-test-snippet.yaml, guide/blueprints/test/example_yaml/testcases/getting-started-test-example.yaml, guide/blueprints/test/usage-examples.md, guide/ops/gui/_my-web-cluster.yaml, guide/ops/gui/_my-web-cluster2.yaml, guide/start/_my-web-cluster.yaml, guide/start/_my-web-cluster2.yaml, guide/start/example_yaml/mycluster.yaml
This update URL to the newest version of example wars, within example blueprints. It also adds `# BROOKLYN_VERSION` tag so that links can be updated when new version of the documentation is published.
=> Update outdated blueprint examples

guide/locations/_location-customizer-security-groups.md
Fix typo in the first YAML example (`:` at the end of the location) + add syntax highlighting
=> Fix typo + syntax highlighting

guide/misc/release-notes.md, package-lock.json
updates to release notes following recent changes to bundles, including https://github.com/apache/brooklyn-server/pull/874
=> release notes updated with recent code changes

guide/blueprints/entity-configuration.md
Some useful change which was sitting for sometime in my workspace.
=> Refer to inheritance.runtime instead of deprecated inheritance.runtime

guide/blueprints/_elect-primary-policies.md
Typo in the elect primary policies gave an incorrect package name.
=> Correct elect primary policies package

guide/blueprints/policies.md
Without the quotes `npm run book` fails cryptically: "template names must be a string: NaN"
=> Quote included file name

README.md, guide/blueprints/catalog/schema.md
Reworks the catalogue schema documentation to make it easier to read and adds a note on how to provide credentials for libraries.
Accompanies https://github.com/apache/brooklyn-server/pull/918.
=> Describe authentication options for catalog libraries

guide/blueprints/clusters.md
Update DynamicCluster docs to add config info and new information from [brooklyn-server#923](https://github.com/apache/brooklyn-server/pull/923).
=> Update DynamicCluster docs

community/gsoc.md, community/index.md
Add a page to the "Community" section which describes Google Summer of Code 2018, and answers some frequently asked questions.
=> Add page with information about GSoC 2018

index.md
Remove the Vagrant-based instructions, which are known to be broken in 0.12.0. Replace with .tar.gz instructions.
=> Fix home page installation instructions

_includes/apache-promo.html, index.md
As requested by Rich Bowen:
On Mon, 9 Apr 2018 at 14:07 Rich Bowen <rbowen@apache.org> wrote:
Dear PMCs,
ApacheCon is our official community event, and is coming up in
September, in Montreal. We need your help getting the word out to your
user communities. (Details at http://apachecon.com/ )
We've made this as easy as possible - it's just a cut-and-paste
snippet that we ask you to add to your site to display the logo of the
nearest future event. That process is documented here:
http://apache.org/events/README.txt  You can see it in action on, for
example, http://httpd.apache.org/
If you follow these steps, it will automatically update for the next
event, and the one after that. We have two other events planned for
this year, and are already working on 5 events for 2019.
Note: If you don't …
=> Add ApacheCon logo button to landing page

_includes/apache-promo.html, index.md, style/css/_landing.scss
=> Update event notice styling

guide/ops/troubleshooting/connectivity.md, guide/ops/troubleshooting/deployment.md, guide/ops/troubleshooting/softwareprocess.md
See https://issues.apache.org/jira/browse/BROOKLYN-588
=> BROOKLYN-588: add to troubleshooting for curl failure 

guide/ops/configuration/brooklyn_cfg.md
In brooklyn classic, one could run `brooklyn generate-password --user ...`. However, that is not possible in brooklyn karaf.
This updates the docs to tell people to use `generate-password.sh`, which we'll need from 1.0.0 (as we'll delete the brooklyn classic distro entirely).
Please first review/merge https://github.com/apache/brooklyn-dist/pull/122
=> Use generate-password.sh script

guide/ops/persistence/index.md
In brooklyn classic, one could run `brooklyn copy-state ...`. This is not supported in brooklyn karaf.
Instead, the REST api can be used. This PR updates the docs to show how to use it.
Please first review/merge https://github.com/apache/brooklyn-server/pull/972, to fix this REST api for usage in karaf!
=> Fix copy-state usage for brooklyn-karaf

guide/ops/persistence/index.md
Based on this comment: https://github.com/apache/brooklyn-docs/pull/258#discussion_r197133399
Note: I checked the docs and this is the only place where we suggested to use `s3cmd`
=> Use the official AWS CLI instead of s3cmd

guide/blueprints/entity-configuration.md, guide/blueprints/example_yaml/appserver-clustered-w-db-concise.yaml, guide/blueprints/example_yaml/appserver-clustered-w-db.yaml, guide/blueprints/example_yaml/appserver-w-db-other-flavor.yaml, guide/blueprints/example_yaml/appserver-w-db.yaml, guide/blueprints/example_yaml/appserver-w-policy.yaml, guide/blueprints/example_yaml/entity-config-app.yaml, guide/blueprints/example_yaml/entity-config-catalog.yaml, guide/blueprints/example_yaml/entity-config-override-app.yaml, guide/blueprints/example_yaml/entity-constraint-app.yaml, guide/blueprints/example_yaml/entity-constraint-catalog.yaml, guide/blueprints/example_yaml/fabric-with-multiple-locations.yaml, guide/blueprints/example_yaml/vanilla-bash-netcat-file.yaml, guide/blueprints/example_yaml/vanilla-bash-netcat-w-client.yaml, guide/blueprints/test/example_yaml/testcases/getting-started-test-example.yaml, guide/ops/cli/cli-usage-guide.md, guide/ops/externalized-configuration.md, guide/ops/gui/_my-web-cluster.yaml, guide/ops/gui/_my-web-cluster2.yaml, guide/start/_my-web-cluster.yaml, guide/start/_my-web-cluster2.yaml
* fix a few typos
* extract some code blocks to `example_yaml`
* fix loading bash script as tar.gz from url to ensure it is executable
* fix hi netcat example to close the connection at end of file
* wrap jdbc string format in quotes
=> Clean up docs

guide/blueprints/java/bundle-dependencies.md
The `Bundle-SymbolicName` and `Bundle-Version` parameters need to be specified to avoid default values being generated that can cause problems when rebinding persisted state.
=> Add note about including parameters when using 'wrap:' prefix

guide/blueprints/java/bundle-dependencies.md
@ahgittin Fix for my not seeing the difference between my editor highlighting trailing spaces and real underscores.
=> Replace underscores with spaces to produce hard line break

guide/dev/tips/logging.md, guide/ops/logging.md
Previously we used logback for logging but this changed to be log4j when
we moved to karaf.  As we now only support karaf most logging is now
done using the log4j framework by default.
This commit updates the docs to reflect the default use of log4j,
=> Update docs to describe log4j setup

Gemfile.lock, README.md, download/index.md, index.md
See http://www.apache.org/foundation/marks/pmcs.html#naming
In particular this part:
<quote>
Every product homepage and any overview download pages for the product
must include a prominent reference to the product as "Apache Foo
software", and must include a brief one sentence description of the
function of the software product itself.
</quote>
=> Add text to comply with Apache naming guidelines

guide/dev/env/maven-build.md
Update required version + build instructions to match the latest changes in Brooklyn
=> Update dev build instructions

download/index.md, download/verify.md
This is a follow up to "Add text to comply with Apache naming guidelines" #280
When I went to push the updated docs to the website I discovered the source and the published website had drifted apart a bit on the download index page and the verify page.
This PR mainly brings the `website` branch back into line with the published site, but also makes another small modification to re-instate the `KEYS` file link, which should exist on the live site but doesn't, and tidies up the introductory text on the verify page a little bit.
There are probably some other things to fix, such as broken links, but that can be done in a separate PR.
=> Update download index and verify files to match published website

Jenkinsfile
As the title says. This should be picked up by https://builds.apache.org/view/B/view/Brooklyn/job/brooklyn-docs/ and build only for PRs, then build and publish for each commit in `website` branch
=> Add Jenkinsfile to build and push automatically the website

guide/SUMMARY.md, guide/blueprints/catalog/quick-launch.md, guide/blueprints/catalog/schema.md
Added documentation snipped to show how entities can be tagged and added to the quick launch. 
The documentation snippet can be found in the `Catalog Items YAML Syntax`
=> Added documentation snippet to show how entities can be tagged and added to Quick Launch

developers/committers/release-process/make-release-artifacts.md, developers/committers/release-process/prerequisites.md, developers/committers/release-process/publish-temp.md, developers/committers/release-process/publish.md, developers/committers/release-process/verify-release-artifacts.md
Meant to do this after https://github.com/apache/brooklyn-dist/pull/150
=> remove references to MD5/SHA1 from release process description

guide/_layouts/website/page.html
I have updated the path for the header used on the documentation site.
I wasn't  showing the Apache Brooklyn text title in the header correctly
=> Path for logo correction

book.json, guide/SUMMARY.md, package.json
Corrected Javadoc link in the template to show the latest URL
Updated current version
Added coercion to use bash for negerate the Javadoc
=> Updated versions and javadoc link

guide/blueprints/advanced-example.md, guide/blueprints/custom-entities.md, guide/blueprints/winrm/index.md
Terminology for the main dashboard is 'components' rather than tabs.
The example for MSSQL is no longer present in the repository linked. If it has been moved elsewhere I've not been able to find out where.
=> Minor update to docs

guide/blueprints/ansible/index.md
=> Use absolute docs paths in ansible guide

guide/blueprints/yaml-reference.md
documentation for brooklyn server PR (reference to follow)
=> add docs for new predicates dsl

guide/blueprints/example_yaml/vanilla-bash-netcat-w-client.yaml
Blueprint used old syntax enricher type which isn't supported in the UI. Changed to type.
=> change enricherType to type

guide/blueprints/workflow/examples/aws-cfn-stacks/index.md
Fixes an incorrectly referenced filename (aws-cfn-type.yaml -> aws-cfn-type.bom)
=> Fixes incorrect filename in aws-cfn-stacks docs

guide/misc/release-notes.md
This is the draft release notes for the 1.1.0 release
=> Draft release notes for 1.1.0

guide/blueprints/chef/creating-blueprints.md, guide/locations/_AWS.md, guide/start/running.md, website/learnmore/theory.md
* oasis camp - now poinitng to the docs as comitee does not seem valid anymore
* removed links to java.com as they throw 403 - I guess everyone looking at brooklyun/amp docs will know how to find main java page anyway
* removed sorting hash for aws console link - not needed in the context
=> fix few more broken links

_includes/head.html, website/learnmore/catalog/catalog-item.html, website/learnmore/catalog/index.html
The Infra team implemented a **_Content Security Policy_** (CSP) at the start of March 2025 which blocks the loading of resources from third parties.
This has blocked the [Brooklyn Website](https://brooklyn.apache.org/) from loading **_bootstrap_** and **_jQuery_** files which has resulted in rendering problems.
Local versions of **_bootstrap_** and **_jQuery_** are already in the style/deps folder and the website just needs to be changed to use them rather than external versions.
=> BROOKLYN-636 FIx Issues the Brooklyn Website caused by the CSP
